# See conda_environment_instructions.md for usage instructions
name: ai_datasets
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - plotnine
  - scikit-learn
  - xgboost
  - folium
  - geopandas
  - plotly
  - pip
  - pip:
      - pytimetk
      - nbformat
      - ipykernel
